// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on

import type { MainIPC } from "./backend/ipc_main";
declare global { //设置全局属性
    const MAIN_WINDOW_VITE_NAME: string;
    const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
    interface Window { //window对象属性
        electronAPI: MainIPC; //加入对象
    }
}